version: '3'
services:
  haproxy:
    build:
      context: .
    environment:
      - PORT[web]=80
      - BACKEND[web]=_http._tcp.latanowicz.com

      - PORT[db]=3363
      - BACKEND[db]=_mysql._tcp.latanowicz.com
